<a href="https://colab.research.google.com/github/ysun155/Math140/blob/main/math140_W1exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random

# To generate random knight move
def gen_random_move():
  new_row = 0
  new_col = 0

  rand_move = random.choice(["up", "down", "right", "left"])
  if rand_move == "up":
    new_col += 2
    if random.choice(["left", "right"]) == "left":
      new_row -= 1
    else:
      new_row += 1
  elif rand_move == "down":
    new_col -= 2
    if random.choice(["left", "right"]) == "left":
      new_row -= 1
    else:
      new_row += 1
  elif rand_move == "right":
    new_row += 2
    if random.choice(["up", "down"]) == "down":
      new_col -= 1
    else:
      new_col += 1
  elif rand_move == "left":
    new_row -= 2
    if random.choice(["up", "down"]) == "down":
      new_col -= 1
    else:
      new_col += 1

  return [new_row, new_col]

# Create chess board, specify its size
rows = 8
columns = 8
chess_board = np.zeros((rows, columns))

# Number of simulation iterations to run
iter = 10000

# To generate random starting position
def gen_init_pos():
  row = random.randint(0, rows)
  column = random.randint(0, columns)

  return [row, column]

# Generates number of moves at each position
def gen_sim():

  curr_pos = gen_init_pos() # Starting in random position

  invalid_move = True

  for i in range(iter):
    while invalid_move:
      try:
        move = gen_random_move()

        chess_board[curr_pos[0]+move[0], curr_pos[1]+move[1]] += 1
        curr_pos = [curr_pos[0]+move[0], curr_pos[1]+move[1]]
        
        invalid_move = False
        break
      except:
        # If generated invalid move
        continue

    invalid_move = True
  
  return chess_board

# Generates ocurrance percentage at each position
def gen_sim_pct():
  for i in range(rows):
    for j in range(columns):
      chess_board[i][j] /= iter

  return chess_board

print(gen_sim())
print(gen_sim_pct())

[[110. 153. 144. 150. 140. 144. 126. 126.]
 [116. 141. 149. 192. 187. 189. 136. 126.]
 [144. 203. 220. 177. 197. 181. 170. 128.]
 [161. 162. 209. 216. 192. 164. 169. 126.]
 [161. 176. 195. 177. 175. 206. 158. 123.]
 [139. 165. 179. 191. 181. 171. 151. 143.]
 [116. 155. 176. 166. 165. 138. 147. 113.]
 [125. 112. 141. 139. 123. 124. 126.  95.]]
[[0.011  0.0153 0.0144 0.015  0.014  0.0144 0.0126 0.0126]
 [0.0116 0.0141 0.0149 0.0192 0.0187 0.0189 0.0136 0.0126]
 [0.0144 0.0203 0.022  0.0177 0.0197 0.0181 0.017  0.0128]
 [0.0161 0.0162 0.0209 0.0216 0.0192 0.0164 0.0169 0.0126]
 [0.0161 0.0176 0.0195 0.0177 0.0175 0.0206 0.0158 0.0123]
 [0.0139 0.0165 0.0179 0.0191 0.0181 0.0171 0.0151 0.0143]
 [0.0116 0.0155 0.0176 0.0166 0.0165 0.0138 0.0147 0.0113]
 [0.0125 0.0112 0.0141 0.0139 0.0123 0.0124 0.0126 0.0095]]
